CREATE TABLE roles (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(20) NOT NULL
)

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fullname VARCHAR2(100) DEFAULT '',
    phone_number VARCHAR2(10) NOT NULL,
    address VARCHAR2(200) DEFAULT '',
    password VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1,
    date_of_birth DATE,
    facebook_account_id NUMBER DEFAULT 0,
    google_account_id NUMBER DEFAULT 0,
    role_id NUMBER,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE tokens (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    token VARCHAR2(255) NOT NULL UNIQUE,
    token_type VARCHAR2(50) NOT NULL,
    expiration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked NUMBER(1) DEFAULT 1 NOT NULL,
    expired NUMBER(1) DEFAULT 1 NOT NULL,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
)

CREATE TABLE social_accounts (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    provider VARCHAR2(20) NOT NULL,
    provider_id VARCHAR2(50) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
)

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) DEFAULT '' NOT NULL
)

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(350),
    price NUMBER(10,2) NOT NULL CHECK(price >= 0),
    description CLOB DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id NUMBER,
    FOREIGN KEY (category_id) REFERENCES categories(id)
)

CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    image_url VARCHAR2(300)
)

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id),
    fullname VARCHAR2(100) DEFAULT '',
    email VARCHAR2(100) DEFAULT '',
    phone_number VARCHAR2(10) NOT NULL,
    address VARCHAR2(200) NOT NULL,
    note VARCHAR2(100) DEFAULT '',
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    total_money NUMBER(10,2) CHECK (total_money >= 0),
    shipping_method VARCHAR2(100),
    shipping_address VARCHAR2(200),
    shipping_date DATE,
    tracking_number VARCHAR2(100),
    payment_method VARCHAR2(100),
    active NUMBER(1) DEFAULT 1
)

CREATE TABLE order_details (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    product_id NUMBER,
    FOREIGN KEY (product_id) REFERENCES products (id),
    price NUMBER(10, 2) CHECK (price >= 0),
    number_of_products NUMBER CHECK (number_of_products > 0),
    total_money NUMBER(10, 2) CHECK (total_money >= 0),
    COLOR VARCHAR2(20) DEFAULT ''
)

--INSERT INTO users(fullname, phone_number, address, password, date_of_birth)
--VALUES('huynh anh khoi', '0935698356', 'hcm', 'password', DATE '2000-07-20');
--
--ALTER TABLE users MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
--
--INSERT INTO roles(id, name)
--VALUES (1, 'user');
--
--INSERT INTO roles(id, name)
--VALUES (2, 'admin');

--DESC users;
--DELETE FROM orders WHERE user_id = 1;
--SELECT * FROM orders WHERE user_id = 1;
--SELECT * FROM users WHERE id = 1;
--DELETE FROM users WHERE id = 1;

--SELECT *
--FROM products
--WHERE id = (
--    SELECT MAX(id)
--    FROM products
--);

--SELECT * FROM products WHERE id = 922;
--UPDATE users SET role_id = 2 WHERE id = 1;


